openapi: 3.0.0
info:
   title: "Transactions API"
   version: 1.0.0

paths:
  /api/transactions:
    get:
      operationId: getTransactionsList
      responses:
        200:
          description: Ok
          content:
            application/json:    
              schema:
                type: array
                items:                
                  $ref: "#/components/schemas/Transaction"
        500:
          description: Something wrong happened
    put:
      operationId: putTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        200:
          description: Ok
        500:
          description: Something wrong happened


components:
  schemas:
    Transaction:
      type: object
      properties:
        message:
          type: string
        from:
          type: string
          format: email
        to:
          type: string
          format: email
        value:
          type: number
          format: double
      required:
        - message
        - from
        - to
        - value
